// Focused unpacked-extension acceptance, using an isolated Chrome profile and synthetic data.
// It never reads the user's profile or contacts the real subscription/server.
import {chromium} from 'playwright';
import {resolve} from 'node:path';
import {mkdir, writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';

const root = resolve('.');
const profile = resolve('work/chrome-acceptance-profile');
await mkdir('work', {recursive: true});
await mkdir('docs/screenshots', {recursive: true});
const extensionPath = resolve('dist/extension');
const context = await chromium.launchPersistentContext(profile, {channel: 'chrome', headless: true, ignoreDefaultArgs: ['--disable-extensions'], args: ['--enable-unsafe-extension-debugging'], viewport: {width: 960, height: 900}});
try {
  const cdp = await context.browser().newBrowserCDPSession();
  const {id} = await cdp.send('Extensions.loadUnpacked', {path: extensionPath});
  const wake = await context.newPage();
  await wake.goto(`chrome-extension://${id}/options.html`);
  const worker = context.serviceWorkers()[0] || await context.waitForEvent('serviceworker');
  await worker.evaluate(() => {
    globalThis.fixture = {proxies: [18443, 18444].map((port, i) => ({name: `示例节点 ${i + 1}`, type: 'http', server: 'bridge.example.invalid', port, tls: true, username: `fixture-${i}`, password: 'synthetic-only'}))};
    const actual = globalThis.fetch;
    globalThis.fetch = (url, options) => String(url).startsWith('https://subscription.example.invalid/') ? Promise.resolve(new Response(JSON.stringify(globalThis.fixture), {status: globalThis.fixtureFailure ? 503 : 200})) : actual(url, options);
  });
  const page = await context.newPage();
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.goto(`chrome-extension://${id}/options.html`);
  await page.locator('#url').fill('https://subscription.example.invalid/test');
  await page.getByRole('button', {name: '保存并更新'}).click();
  await page.getByText('2 条可用线路').waitFor();
  await page.locator('#rules-panel > summary').click();
  await page.locator('#proxy').fill('example.com');
  await page.locator('#direct').fill('local.example.com');
  await page.getByRole('button', {name: '保存规则'}).click();
  await page.waitForFunction(() => !document.getElementById('save-rules').disabled);
  await page.screenshot({path: resolve('docs/screenshots/settings.png'), fullPage: true});
  await page.goto(`chrome-extension://${id}/popup.html`);
  await page.locator('#node').selectOption('bridge.example.invalid:18443');
  await page.getByRole('button', {name: '连接', exact: true}).click();
  await page.getByText('代理已启用', {exact: true}).waitFor();
  let applied = await worker.evaluate(() => chrome.proxy.settings.get({incognito: false}));
  assert.equal(applied.levelOfControl, 'controlled_by_this_extension');
  assert.equal(applied.value.pacScript.mandatory, true);
  assert.ok(applied.value.pacScript.data.includes('HTTPS bridge.example.invalid:18443'));
  await page.setViewportSize({width: 380, height: 510});
  await page.screenshot({path: resolve('docs/screenshots/popup.png')});
  await page.locator('#node').selectOption('bridge.example.invalid:18444');
  await page.getByText('代理已启用', {exact: true}).waitFor();
  applied = await worker.evaluate(() => chrome.proxy.settings.get({incognito: false}));
  assert.ok(applied.value.pacScript.data.includes('HTTPS bridge.example.invalid:18444'));
  await worker.evaluate(() => { globalThis.fixture = {proxies: []}; });
  await page.getByRole('button', {name: '更新订阅'}).click();
  await page.getByText('当前节点已被移除', {exact: true}).waitFor();
  applied = await worker.evaluate(() => chrome.proxy.settings.get({incognito: false}));
  assert.ok(applied.value.pacScript.data.includes('PROXY 127.0.0.1:1'));
  await page.getByRole('button', {name: '断开', exact: true}).click();
  await page.getByText('关闭', {exact: true}).waitFor();
  applied = await worker.evaluate(() => chrome.proxy.settings.get({incognito: false}));
  assert.notEqual(applied.levelOfControl, 'controlled_by_this_extension');
  await worker.evaluate(() => { globalThis.fixture={proxies:[{name:'Cache fixture',type:'http',server:'bridge.example.invalid',port:18443,tls:true,username:'fixture',password:'synthetic-only'}]}; });
  await page.getByRole('button', {name:'更新订阅'}).click();
  await page.getByText('1 条可用线路').waitFor();
  const cached=await worker.evaluate(async () => (await chrome.storage.local.get('config')).config);
  await worker.evaluate(()=>{globalThis.fixtureFailure=true;});
  await page.getByRole('button', {name:'更新订阅'}).click();
  await page.locator('#error').filter({hasText:'订阅更新失败'}).waitFor();
  const retained=await worker.evaluate(async () => (await chrome.storage.local.get('config')).config);
  assert.equal(retained.updatedAt,cached.updatedAt); assert.equal(retained.nodes[0].id,cached.nodes[0].id);
  const conflictPath=resolve('work/conflict-fixture');
  await mkdir(conflictPath,{recursive:true});
  await writeFile(resolve(conflictPath,'manifest.json'),JSON.stringify({manifest_version:3,name:'Acceptance proxy controller',version:'1.0',permissions:['proxy'],background:{service_worker:'background.js'}}));
  await writeFile(resolve(conflictPath,'background.js'),"chrome.runtime.onInstalled.addListener(()=>chrome.proxy.settings.set({value:{mode:'direct'},scope:'regular'}));");
  const conflict=await cdp.send('Extensions.loadUnpacked',{path:conflictPath});
  const other=context.serviceWorkers().find(w=>new URL(w.url()).hostname===conflict.id) || await context.waitForEvent('serviceworker',{predicate:w=>new URL(w.url()).hostname===conflict.id});
  await other.evaluate(()=>chrome.proxy.settings.set({value:{mode:'direct'},scope:'regular'}));
  await page.locator('#node').selectOption('bridge.example.invalid:18443');
  await page.getByRole('button', {name:'连接',exact:true}).click();
  await page.getByText('代理控制冲突',{exact:true}).waitFor();
  assert.equal((await other.evaluate(()=>chrome.proxy.settings.get({incognito:false}))).levelOfControl,'controlled_by_this_extension');
  await page.getByRole('button',{name:'断开',exact:true}).click();
  await page.getByText('关闭',{exact:true}).waitFor();
  assert.equal((await other.evaluate(()=>chrome.proxy.settings.get({incognito:false}))).levelOfControl,'controlled_by_this_extension');
  await other.evaluate(()=>chrome.proxy.settings.clear({scope:'regular'}));
  await cdp.send('Extensions.uninstall',{id:conflict.id});
  assert.deepEqual(errors, []);
  await writeFile('work/chrome-acceptance.json', JSON.stringify({result: 'passed', checks: ['unpacked MV3 loading', 'subscription import UI', 'custom rule save', 'real Chrome PAC application', 'endpoint switching', 'removed selection blocked', 'disconnect releases proxy', 'failed refresh retains cache', 'other extension control preserved'], realServerContacted: false}, null, 2));
  console.log('Passed isolated Chrome extension acceptance. No live-server requests were made.');
} finally { await context.close(); }
